# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 20:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='owner',
        ),
    ]
