# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0003_auto_20160317_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='finish_time',
            field=models.DurationField(),
        ),
    ]
