# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0004_auto_20160317_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='finish_time',
            field=models.TimeField(verbose_name='%H:%M:%S'),
        ),
    ]
