# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0005_auto_20160318_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='finish_time',
            field=models.TimeField(),
        ),
    ]
