# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0006_auto_20160318_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='avg_pulse',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='participant',
            name='cadence',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='participant',
            name='max_pulse',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
    ]
