# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0011_auto_20160318_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='place',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
