# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 15:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0012_participant_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_age', models.PositiveSmallIntegerField()),
                ('max_age', models.PositiveSmallIntegerField()),
                ('last_modified', models.DateField(auto_now=True)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='race.Race')),
            ],
        ),
    ]
