# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0014_auto_20160319_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racecategory',
            name='max_age',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='racecategory',
            name='min_age',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
    ]
