# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 19:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0015_auto_20160319_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='race.RaceCategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='racecategory',
            name='max_age',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='racecategory',
            name='min_age',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
