# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0017_auto_20160319_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='age',
            field=models.PositiveSmallIntegerField(default=16),
            preserve_default=False,
        ),
    ]
