# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0019_auto_20160320_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaceTiming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_started', models.DateTimeField(auto_now_add=True)),
                ('time_stopped', models.DateTimeField(blank=True, null=True)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='race.Race')),
            ],
        ),
    ]
