# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0020_racetiming'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='finish_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
