# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0021_auto_20160327_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='place',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
